/**
 * The Supabase connection, and the translation between what the app holds in
 * memory and what the database stores.
 *
 * The cloud is OPTIONAL everywhere. With no environment variables set, every
 * function here reports "not configured" and the app carries on exactly as it did
 * before — localStorage only. That is not politeness, it is how the free tier
 * works and how the thing stays developable without a network.
 *
 * On keys: the publishable key is meant to be in the bundle. It is a public
 * identifier, not a secret, and it authorises nothing by itself — the row level
 * security policies in supabase/01-schema.sql are the boundary. The secret /
 * service role key is the opposite of that and must never appear in this folder.
 */
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import type { Doc } from "./model.js";
import type { Metrics, Platform, Post, Stage } from "./pipeline.js";

const URL = import.meta.env.VITE_SUPABASE_URL?.trim();
// Supabase is moving projects from the legacy JWT `anon` key to sb_publishable_*.
// Both authorise the same thing — nothing, on their own — so either is accepted
// and a key copied from today's dashboard works without renaming anything.
const ANON =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ??
  import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

export const isCloudConfigured = (): boolean => Boolean(URL && ANON);

let client: SupabaseClient | null = null;

/** Null when unconfigured, so every caller has to decide what offline means. */
export function cloud(): SupabaseClient | null {
  if (!isCloudConfigured()) return null;
  client ??= createClient(URL!, ANON!, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      // The magic link lands back on the app with the session in the URL.
      detectSessionInUrl: true,
    },
  });
  return client;
}

export type Plan = "free" | "pro" | "agency";

export type Profile = {
  id: string;
  email: string | null;
  displayName: string | null;
  plan: Plan;
  planRenewsAt: string | null;
};

/* ── row shapes ───────────────────────────────────────────────────────────── */

export type DocRow = {
  user_id: string;
  id: string;
  name: string;
  width: number;
  height: number;
  slide_count: number;
  background: string | null;
  doc_group: string | null;
  framework: string | null;
  style_id: string | null;
  data: Doc;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
};

export type PostRow = {
  user_id: string;
  id: string;
  doc_id: string | null;
  title: string;
  stage: Stage;
  platform: Platform;
  framework: string | null;
  slide_count: number;
  hook: string;
  style_id: string | null;
  scheduled_for: string | null;
  posted_at: string | null;
  url: string | null;
  caption: string;
  notes: string;
  metrics: Metrics | null;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
  /** Generated by Postgres from `metrics`. Present on reads, never written. */
  impressions?: number | null;
};

/* ── docs ─────────────────────────────────────────────────────────────────── */

/**
 * The flat columns are a projection of `data`, kept so the project grid can be
 * drawn without downloading every slide. `data` stays the truth; if the two ever
 * disagree, the blob wins, because that is what the editor opens.
 */
export function docToRow(doc: Doc, userId: string, deletedAt: string | null = null): DocRow {
  return {
    user_id: userId,
    id: doc.id,
    name: doc.name,
    width: doc.width,
    height: doc.height,
    slide_count: doc.slides.length,
    background: doc.slides[0]?.background ?? null,
    doc_group: doc.group ?? null,
    framework: doc.framework ?? null,
    style_id: doc.styleId ?? null,
    data: doc,
    created_at: doc.createdAt,
    updated_at: doc.updatedAt,
    // Server-owned; sent only to satisfy the type and overwritten by the trigger.
    server_updated_at: doc.updatedAt,
    deleted_at: deletedAt,
  };
}

export const rowToDoc = (row: DocRow): Doc => ({
  ...row.data,
  id: row.id,
  name: row.name,
  updatedAt: row.updated_at,
  ...(row.doc_group ? { group: row.doc_group } : {}),
  ...(row.framework ? { framework: row.framework } : {}),
  ...(row.style_id ? { styleId: row.style_id } : {}),
});

/* ── posts ────────────────────────────────────────────────────────────────── */

export function postToRow(post: Post, userId: string, deletedAt: string | null = null): PostRow {
  return {
    user_id: userId,
    id: post.id,
    doc_id: post.docId,
    title: post.title,
    stage: post.stage,
    platform: post.platform,
    framework: post.framework,
    slide_count: post.slideCount,
    hook: post.hook,
    style_id: post.styleId,
    scheduled_for: post.scheduledFor,
    posted_at: post.postedAt,
    url: post.url,
    caption: post.caption,
    notes: post.notes,
    metrics: post.metrics,
    created_at: post.createdAt,
    updated_at: post.updatedAt,
    server_updated_at: post.updatedAt,
    deleted_at: deletedAt,
  };
}

export const rowToPost = (row: PostRow): Post => ({
  id: row.id,
  docId: row.doc_id,
  title: row.title,
  stage: row.stage,
  platform: row.platform,
  framework: row.framework,
  slideCount: row.slide_count,
  hook: row.hook,
  styleId: row.style_id,
  scheduledFor: row.scheduled_for,
  postedAt: row.posted_at,
  url: row.url,
  caption: row.caption,
  notes: row.notes,
  metrics: row.metrics,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

/**
 * Strips the columns the database owns before a write.
 *
 * `impressions` is generated from `metrics` and Postgres rejects any attempt to
 * set it; `server_updated_at` is the sync clock and is stamped by a trigger. Both
 * come back on every select, so a pulled row that gets edited and pushed again
 * would carry them — and the only symptom is a 400 from PostgREST that reads like
 * a schema mismatch. Cheaper to strip once here than to debug at each call site.
 */
export const forWrite = <T extends object>(row: T): Omit<T, "impressions" | "server_updated_at"> => {
  const { impressions: _generated, server_updated_at: _clock, ...rest } = row as T & {
    impressions?: number | null;
    server_updated_at?: string;
  };
  return rest;
};
