/**
 * The Supabase connection, and the translation between what the app holds in
 * memory and what the database stores.
 *
 * The cloud is OPTIONAL everywhere. With no environment variables set, every
 * function here reports "not configured" and the app carries on exactly as it did
 * before, localStorage only. That is not politeness, it is how the free tier
 * works and how the thing stays developable without a network.
 *
 * On keys: the publishable key is meant to be in the bundle. It is a public
 * identifier, not a secret, and it authorises nothing by itself, the row level
 * security policies in supabase/01-schema.sql are the boundary. The secret /
 * service role key is the opposite of that and must never appear in this folder.
 */
import { createClient, type SupabaseClient } from "@supabase/supabase-js";

import type { Asset, AssetKind, LogoRole } from "./assets.js";
import type { Brand } from "./brand.js";
import type { Client } from "./clients.js";
import type { Doc } from "./model.js";
import type { Metrics, Platform, Post, Stage } from "./pipeline.js";

const URL = import.meta.env.VITE_SUPABASE_URL?.trim();
// Supabase is moving projects from the legacy JWT `anon` key to sb_publishable_*.
// Both authorise the same thing, nothing, on their own, so either is accepted
// and a key copied from today's dashboard works without renaming anything.
const ANON =
  import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() ??
  import.meta.env.VITE_SUPABASE_ANON_KEY?.trim();

export const isCloudConfigured = (): boolean => Boolean(URL && ANON);

let client: SupabaseClient | null = null;

/** Null when unconfigured, so every caller has to decide what offline means. */
export function cloud(): SupabaseClient | null {
  if (!isCloudConfigured()) return null;
  client ??= createClient(URL!, ANON!, {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      /*
       * PKCE, not the implicit flow supabase-js defaults to.
       *
       * The difference is what comes back in the URL. Implicit returns
       * `#access_token=...&refresh_token=...`, the real, long-lived credential,
       * sitting in browser history and readable by anything running on the page.
       * The fragment never reaches a server, which is the only reason that was
       * tolerable at all.
       *
       * PKCE returns `?code=...`: one-time, and worthless without a verifier
       * this browser generated and kept to itself. A link copied out of an inbox
       * and opened somewhere else cannot be redeemed.
       *
       * The cost is real and is why the code path below exists: the verifier
       * lives in the browser that ASKED, so a link opened on a different device
       * fails. Six digits typed into the original tab has neither problem.
       */
      flowType: "pkce",
      detectSessionInUrl: true,
    },
  });
  return client;
}

export type Plan = "free" | "pro" | "agency";

export type Profile = {
  id: string;
  email: string | null;
  displayName: string | null;
  plan: Plan;
  /** When the current period ends. What happens then depends on the next field. */
  planRenewsAt: string | null;
  /** True when that date is the END rather than the next charge. */
  planEndsAtPeriodEnd: boolean;
  /** Stripe has a customer for them, so the billing portal has something to show. */
  hasBilling: boolean;
};

/* ── row shapes ───────────────────────────────────────────────────────────── */

export type DocRow = {
  user_id: string;
  id: string;
  name: string;
  width: number;
  height: number;
  slide_count: number;
  background: string | null;
  doc_group: string | null;
  client_id: string | null;
  framework: string | null;
  style_id: string | null;
  series_id: string | null;
  series_part: number | null;
  data: Doc;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
};

export type PostRow = {
  user_id: string;
  id: string;
  doc_id: string | null;
  title: string;
  stage: Stage;
  platform: Platform;
  framework: string | null;
  slide_count: number;
  hook: string;
  style_id: string | null;
  client_id: string | null;
  series_id: string | null;
  series_part: number | null;
  scheduled_for: string | null;
  posted_at: string | null;
  url: string | null;
  caption: string;
  notes: string;
  pillar: string;
  campaign: string;
  objective: string | null;
  reviewer: string;
  approval_notes: string;
  metrics: Metrics | null;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
  /** Generated by Postgres from `metrics`. Present on reads, never written. */
  impressions?: number | null;
};

export type BrandRow = {
  user_id: string;
  id: string;
  name: string;
  /** The whole Theme. Nothing queries inside it, so flat columns would only drift. */
  theme: Brand["theme"];
  /** Asset ids, by variant. See 04-storage.sql for why this is not three columns. */
  logos: Record<string, string>;
  /** Tone, samples and banned words. jsonb for the same reason `theme` is. */
  voice: Record<string, unknown> | null;
  client_id: string | null;
  width: number;
  height: number;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
};

/* ── brands ───────────────────────────────────────────────── */

export const brandToRow = (
  brand: Brand,
  userId: string,
  deletedAt: string | null = null,
): BrandRow => ({
  user_id: userId,
  id: brand.id,
  name: brand.name,
  theme: brand.theme,
  logos: brand.logos ?? {},
  voice: brand.voice ?? null,
  client_id: brand.clientId ?? null,
  width: brand.width,
  height: brand.height,
  created_at: brand.createdAt,
  updated_at: brand.updatedAt,
  server_updated_at: brand.updatedAt,
  deleted_at: deletedAt,
});

export const rowToBrand = (row: BrandRow): Brand => ({
  id: row.id,
  name: row.name,
  theme: row.theme,
  // The column arrives with 04-storage.sql; a project that has not run it yet
  // simply has no logos, which is the same as a brand that never had one.
  logos: row.logos ?? {},
  // The column arrives with 10-brand-voice.sql; absent reads as no voice,
  // which is what a brand made before it had one.
  ...(row.voice ? { voice: row.voice as Brand["voice"] } : {}),
  ...(row.client_id ? { clientId: row.client_id } : {}),
  width: row.width,
  height: row.height,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

/* ── docs ─────────────────────────────────────────────────────────────────── */

/**
 * The flat columns are a projection of `data`, kept so the project grid can be
 * drawn without downloading every slide. `data` stays the truth; if the two ever
 * disagree, the blob wins, because that is what the editor opens.
 */
export function docToRow(doc: Doc, userId: string, deletedAt: string | null = null): DocRow {
  return {
    user_id: userId,
    id: doc.id,
    name: doc.name,
    width: doc.width,
    height: doc.height,
    slide_count: doc.slides.length,
    background: doc.slides[0]?.background ?? null,
    doc_group: doc.group ?? null,
    client_id: doc.clientId ?? null,
    framework: doc.framework ?? null,
    style_id: doc.styleId ?? null,
    series_id: doc.series?.id ?? null,
    series_part: doc.series?.part ?? null,
    data: doc,
    created_at: doc.createdAt,
    updated_at: doc.updatedAt,
    // Server-owned; sent only to satisfy the type and overwritten by the trigger.
    server_updated_at: doc.updatedAt,
    deleted_at: deletedAt,
  };
}

export const rowToDoc = (row: DocRow): Doc => ({
  ...row.data,
  id: row.id,
  name: row.name,
  updatedAt: row.updated_at,
  ...(row.doc_group ? { group: row.doc_group } : {}),
  ...(row.client_id ? { clientId: row.client_id } : {}),
  ...(row.framework ? { framework: row.framework } : {}),
  ...(row.style_id ? { styleId: row.style_id } : {}),
  // The columns arrive with 05-series.sql. Until then `data` still carries it,
  // which the spread above has already applied, so a project that has not run
  // the migration keeps its series locally and simply cannot query by it.
  ...(row.series_id && row.series_part
    ? { series: { id: row.series_id, part: row.series_part } }
    : {}),
});

/* ── posts ────────────────────────────────────────────────────────────────── */

export function postToRow(post: Post, userId: string, deletedAt: string | null = null): PostRow {
  return {
    user_id: userId,
    id: post.id,
    doc_id: post.docId,
    title: post.title,
    stage: post.stage,
    platform: post.platform,
    framework: post.framework,
    slide_count: post.slideCount,
    hook: post.hook,
    style_id: post.styleId,
    client_id: post.clientId ?? null,
    series_id: post.series?.id ?? null,
    series_part: post.series?.part ?? null,
    scheduled_for: post.scheduledFor,
    posted_at: post.postedAt,
    url: post.url,
    caption: post.caption,
    notes: post.notes,
    pillar: post.pillar,
    campaign: post.campaign,
    objective: post.objective,
    reviewer: post.reviewer,
    approval_notes: post.approvalNotes,
    metrics: post.metrics,
    created_at: post.createdAt,
    updated_at: post.updatedAt,
    server_updated_at: post.updatedAt,
    deleted_at: deletedAt,
  };
}

export const rowToPost = (row: PostRow): Post => ({
  id: row.id,
  docId: row.doc_id,
  title: row.title,
  stage: row.stage,
  platform: row.platform,
  framework: row.framework,
  slideCount: row.slide_count,
  hook: row.hook,
  styleId: row.style_id,
  ...(row.client_id ? { clientId: row.client_id } : {}),
  series: row.series_id && row.series_part ? { id: row.series_id, part: row.series_part } : null,
  scheduledFor: row.scheduled_for,
  postedAt: row.posted_at,
  url: row.url,
  caption: row.caption,
  notes: row.notes,
  // The columns arrive with 08-pipeline-fields.sql; until then they read as
  // empty, which is what they are.
  pillar: row.pillar ?? "",
  campaign: row.campaign ?? "",
  objective: (row.objective as Post["objective"]) ?? null,
  reviewer: row.reviewer ?? "",
  approvalNotes: row.approval_notes ?? "",
  metrics: row.metrics,
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

/**
 * Strips the columns the database owns before a write.
 *
 * `impressions` is generated from `metrics` and Postgres rejects any attempt to
 * set it; `server_updated_at` is the sync clock and is stamped by a trigger. Both
 * come back on every select, so a pulled row that gets edited and pushed again
 * would carry them, and the only symptom is a 400 from PostgREST that reads like
 * a schema mismatch. Cheaper to strip once here than to debug at each call site.
 */
export const forWrite = <T extends object>(row: T): Omit<T, "impressions" | "server_updated_at"> => {
  const { impressions: _generated, server_updated_at: _clock, ...rest } = row as T & {
    impressions?: number | null;
    server_updated_at?: string;
  };
  return rest;
};

/* ── assets ───────────────────────────────────────────────────────────────── */

export type AssetRow = {
  user_id: string;
  id: string;
  kind: AssetKind;
  name: string;
  path: string;
  mime: string;
  content_key: string | null;
  width: number | null;
  height: number | null;
  bytes: number;
  family: string | null;
  brand_id: string | null;
  client_id: string | null;
  role: LogoRole | null;
  folder: string | null;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
};

export const assetToRow = (
  asset: Asset,
  userId: string,
  deletedAt: string | null = null,
): AssetRow => ({
  user_id: userId,
  id: asset.id,
  kind: asset.kind,
  name: asset.name,
  path: asset.path,
  mime: asset.mime,
  content_key: asset.key ?? null,
  width: asset.w ?? null,
  height: asset.h ?? null,
  bytes: asset.bytes,
  family: asset.family ?? null,
  brand_id: asset.brandId ?? null,
  client_id: asset.clientId ?? null,
  role: asset.role ?? null,
  folder: asset.folder ?? null,
  created_at: asset.createdAt,
  updated_at: asset.updatedAt,
  server_updated_at: asset.updatedAt,
  deleted_at: deletedAt,
});

/**
 * `data` is deliberately not restored on the way back.
 *
 * A row that came from the server has its bytes in the bucket by definition, and
 * carrying an inline copy as well would put the megabytes this whole batch
 * removes straight back into localStorage.
 */
export const rowToAsset = (row: AssetRow): Asset => ({
  id: row.id,
  kind: row.kind,
  name: row.name,
  path: row.path,
  mime: row.mime,
  bytes: row.bytes,
  ...(row.content_key === null ? {} : { key: row.content_key }),
  ...(row.width === null ? {} : { w: row.width }),
  ...(row.height === null ? {} : { h: row.height }),
  ...(row.family === null ? {} : { family: row.family }),
  ...(row.brand_id === null ? {} : { brandId: row.brand_id }),
  ...(row.client_id === null ? {} : { clientId: row.client_id }),
  ...(row.role === null ? {} : { role: row.role }),
  ...(row.folder === null ? {} : { folder: row.folder }),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});

/* ── storage ──────────────────────────────────────────────────────────────── */

export const MEDIA_BUCKET = "media";
export const SLIDES_BUCKET = "slides";

/**
 * A week.
 *
 * Long enough that a document opened, edited and reopened over a working week
 * never blinks, short enough that a URL pasted into a chat does not become a
 * permanent public handle on a private file. Every open re-signs anyway, so this
 * is a grace period rather than a lifetime.
 */
export const SIGNED_TTL_SECONDS = 7 * 24 * 60 * 60;

export type UploadResult = { ok: true; path: string } | { ok: false; error: string };

/** Storage is only there when both the project and the session are. */
export const storageReady = (): boolean => isCloudConfigured();

export async function uploadObject(
  bucket: string,
  path: string,
  bytes: Uint8Array,
  mime: string,
): Promise<UploadResult> {
  const db = cloud();
  if (!db) return { ok: false, error: "Cloud is not configured" };

  // `upsert` so re-uploading the same asset id replaces it rather than failing.
  // A bucket that has not been created yet answers "Bucket not found", which is
  // the one error worth naming: it means 04-storage.sql has not been run.
  const { error } = await db.storage.from(bucket).upload(path, bytes as BlobPart, {
    contentType: mime,
    upsert: true,
  });

  if (error) {
    const missing = /bucket not found/i.test(error.message);
    return {
      ok: false,
      error: missing
        ? "The media bucket does not exist yet. Run supabase/04-storage.sql."
        : error.message,
    };
  }
  return { ok: true, path };
}

/**
 * Signed URLs for a whole document's worth of assets, in one round trip.
 *
 * One call rather than one per image is the difference between opening a
 * ten-picture carousel in a tick and opening it in ten. Paths that fail to sign
 * are simply absent from the map, and the caller keeps whatever `src` it had.
 */
export async function signPaths(paths: readonly string[]): Promise<Map<string, string>> {
  const out = new Map<string, string>();
  const db = cloud();
  if (!db || paths.length === 0) return out;

  const { data, error } = await db.storage
    .from(MEDIA_BUCKET)
    .createSignedUrls([...paths], SIGNED_TTL_SECONDS);
  if (error || !data) return out;

  for (const entry of data) {
    if (entry.signedUrl && entry.path) out.set(entry.path, entry.signedUrl);
  }
  return out;
}

export async function removeObjects(bucket: string, paths: readonly string[]): Promise<void> {
  const db = cloud();
  if (!db || paths.length === 0) return;
  await db.storage.from(bucket).remove([...paths]);
}

/**
 * The public address of a published slide.
 *
 * Built by the client rather than fetched, because `getPublicUrl` is a pure
 * string join over the project URL and a round trip for one would be silly.
 */
export function publicUrl(bucket: string, path: string): string {
  const db = cloud();
  if (!db) return "";
  return db.storage.from(bucket).getPublicUrl(path).data.publicUrl;
}

/* ── clients ──────────────────────────────────────────────────────────────── */

export type ClientRow = {
  user_id: string;
  id: string;
  name: string;
  colour: string;
  brand_id: string | null;
  archived: boolean;
  created_at: string;
  updated_at: string;
  server_updated_at: string;
  deleted_at: string | null;
};

export const clientToRow = (
  client: Client,
  userId: string,
  deletedAt: string | null = null,
): ClientRow => ({
  user_id: userId,
  id: client.id,
  name: client.name,
  colour: client.colour,
  brand_id: client.brandId ?? null,
  archived: client.archived ?? false,
  created_at: client.createdAt,
  updated_at: client.updatedAt,
  server_updated_at: client.updatedAt,
  deleted_at: deletedAt,
});

export const rowToClient = (row: ClientRow): Client => ({
  id: row.id,
  name: row.name,
  colour: row.colour,
  ...(row.brand_id === null ? {} : { brandId: row.brand_id }),
  ...(row.archived ? { archived: true } : {}),
  createdAt: row.created_at,
  updatedAt: row.updated_at,
});
